### ISSUE TITLE
The "it" block skips when no description is provided.

### ISSUE THREAD

**Issue by cnishina** [webdriverio-boneyard/wdio-jasmine-framework#130]
### This test skips
```
describe('', () => {
  it('', () => {  // No description skips this test.
    console.log('We got here!');
  });
});
```

### This test works
```
describe('', () => {
  it('some text', () => {
    console.log('We got here!');
  });
});
```

In Jasmine the skipped test in the first example usually works. Is this as designed?

See https://github.com/cnishina/wdm-webdriverio/tree/fix_adapter/ for an example.

**Comment by BorisOsipov** [comment]
Hi @cnishina,

Looks like a bug.

**Comment by cnishina** [comment]
So I think I can fix this. We are filtering for some truthiness to the following:

https://github.com/webdriverio-boneyard/wdio-jasmine-framework/blob/master/lib/adapter.js#L77

Maybe something simple like this:

```
var newArgs = [specTitle, patchedOrigFn, retryCnt].filter(function (a) {
  if (a === '') {
    return true;
  } else {
    return Boolean(a);
  }
});
```

Running this locally I run the previously skipped tests. Is this the right place to do this?

**Comment by BorisOsipov** [comment]
Yes it's ok. Thanks to investigate this 👍

**Comment by cnishina** [comment]
Cool. I'll have a PR in later today.

**Comment by christian-bromann** [comment]
Let's continue convo in #131
